version: '3.2'
services:
  mscglobal:
    build: ../
    environment:
      - PORT=3000
  cypress:
    image: "cypress/included:3.2.0"
    depends_on:
      - mscglobal
    environment:
      - CYPRESS_baseUrl=http://localhost:3000
    working_dir: /e2e
    volumes:
      - ./:/e2e
